package note

/*
* @CreateTime: 2021/1/12 18:47
* @Author: JemmyHu <hujm20151021@gmail.com>
* @Description: define variables here
 */

const (
	// appName ...
	appName = "Terminal Notebook"
	// version ...
	version = "v2.0.0"
	// appHome is the folder name for App
	appHome = ".terminal_note"

	// idLayout use timestamp as note id
	idLayout = "20060102150405"

	// dbFileNameTemplate local file to save a notebook
	dbFileNameTemplate = ".terminal_note_%s.db"
	// dbBucket bucket name to save all notes in a notebook
	dbBucket = "diary"
	// dbHeadKey default key to save the first tip note, which is generated default
	dbHeadKey = "head"
	// dbTailKey default key to save the last tip note, which is generated default
	dbTailKey = "tail"

	headContent = "start"
	tailContent = "end"

	rsaBits        = 2048
	pubKeyTempName = "terminal_note_%s_rsa.pub"
	prvTempName    = "terminal_note_%s_rsa"
)

// GetAppName ...
func GetAppName() string {
	return appName
}

// GetVersion ...
func GetVersion() string {
	return version
}

// GetDbBucketName returns default bucket name for a notebook.
func GetDbBucketName() string {
	return dbBucket
}

// GetDbHeadKey ...
func GetDbHeadKey() string {
	return dbHeadKey
}

// GetDbTailKey ...
func GetDbTailKey() string {
	return dbTailKey
}

// GetHeadDefaultContent returns content for the first note generated by system.
func GetHeadDefaultContent() string {
	return headContent
}

// GetTailDefaultContent returns content for the last note generated by system.
func GetTailDefaultContent() string {
	return tailContent
}

// GetAppHome ...
func GetAppHome() string {
	return appHome
}

// GetPubKeyName ...
func GetPubKeyName() string {
	return pubKeyTempName
}

// GetPrivateKeyName ...
func GetPrivateKeyName() string {
	return prvTempName
}
